In [ ]:
pip install geemap

     |████████████████████████████████| 450kB 3.7MB/s 
     |████████████████████████████████| 81kB 3.8MB/s 
     |████████████████████████████████| 1.6MB 5.1MB/s 
     |████████████████████████████████| 225kB 10.0MB/s 
     |████████████████████████████████| 102kB 6.2MB/s 
     |████████████████████████████████| 1.3MB 11.3MB/s 
     |████████████████████████████████| 102kB 7.6MB/s 
     |████████████████████████████████| 1.2MB 18.5MB/s 
     |████████████████████████████████| 5.1MB 24.0MB/s 
     |████████████████████████████████| 143kB 49.9MB/s 
     |████████████████████████████████| 552kB 33.0MB/s 
     |████████████████████████████████| 378kB 51.1MB/s 
     |████████████████████████████████| 122kB 43.5MB/s 
     |████████████████████████████████| 122kB 47.0MB/s 
     |████████████████████████████████| 71kB 6.6MB/s 
     |████████████████████████████████| 71kB 6.0MB/s 
     |████████████████████████████████| 430kB 36.3MB/s 
  Created wheel for ipynb-py-convert: filename=ipynb_py_co

In [ ]:
import ee
import geemap
import os

In [ ]:
Map = geemap.Map()
Map

To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

    https://accounts.google.com/o/oauth2/auth?client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&code_challenge=ta5Eq2533mlv1oC5X6CtnjoqGO5wOH5jbZWUEglwdtw&code_challenge_method=S256

The authorization workflow will generate a code, which you should paste in the box below. 
Enter verification code: 4/1AY0e-g5SnYam66zoFK2jzqRvZh1jvVuLTRsx4mleUALVcoDhvCJSJGGDNcc

Successfully saved authorization token.


In [ ]:
#loc1 = ee.Geometry.Polygon([ [75.45157492160797,30.634404129904425],[75.4524278640747,30.63372099804389],
#                             [75.45236885547638,30.634399514164798],[75.45157492160797,30.634404129904425] ])
#loc2 = ee.Geometry.Polygon([ [85.85590660572052,26.093581136401006],[85.85663080215454,26.09337879451938 ],
#                             [85.85686147212981,26.094009907326967],[85.85622847080231,26.09425078918021]  ])
#loc3 = ee.Geometry.Polygon([ [78.6662346124649,17.6686911655875],[78.6662346124649,17.66929686130703],
#                             [78.66571158170699,17.66929686130703],[78.66571158170699,17.66869116558751]  ])

In [ ]:
loc = ee.Geometry.Polygon([
                           [[85.85622847080231, 26.09425078918021], [85.85590660572052, 26.093581136401006], 
                             [85.85663080215454, 26.09337879451938], [85.85686147212981, 26.094009907326967]]
                           ])

collection = ee.ImageCollection("LANDSAT/LC08/C01/T1") \
    .filterBounds(loc) \
    .filterDate('2020-01-01', '2020-06-30') #\
#    .filter(ee.Filter.metadata_("CLOUD_COVER", "less_than", 10))

In [ ]:
print(collection.aggregate_array('system:index').getInfo())

['LC08_140042_20200115', 'LC08_140042_20200131', 'LC08_140042_20200216', 'LC08_140042_20200303', 'LC08_140042_20200319', 'LC08_140042_20200404', 'LC08_140042_20200420', 'LC08_140042_20200506', 'LC08_140042_20200607', 'LC08_141042_20200106', 'LC08_141042_20200122', 'LC08_141042_20200207', 'LC08_141042_20200223', 'LC08_141042_20200310', 'LC08_141042_20200326', 'LC08_141042_20200411', 'LC08_141042_20200513', 'LC08_141042_20200529']


In [ ]:
list = collection.aggregate_array('system:index').getInfo()
image_scene = list[0:9]
print(image_scene)

['LC08_140042_20200115', 'LC08_140042_20200131', 'LC08_140042_20200216', 'LC08_140042_20200303', 'LC08_140042_20200319', 'LC08_140042_20200404', 'LC08_140042_20200420', 'LC08_140042_20200506', 'LC08_140042_20200607']


In [ ]:
import os
from google.colab import drive 
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#%cd /content/drive/My\ Drive/Colab Notebooks

In [ ]:
#for scene in image_scene[0:1]:
  #print('LANDSAT/LC08/C01/T1/'+scene)
 # image = ee.Image('LANDSAT/LC08/C01/T1/'+scene)
 # Map.addLayer(image, vis_params={'bands': ['B4', 'B3', 'B2']}, name='landsat_geemap', shown=True, opacity=0.7)

In [ ]:
for scene in image_scene:
  data1 = ee.Image('LANDSAT/LC08/C01/T1/'+scene)
  roi = loc
  geemap.ee_export_image_to_drive(data1, description='%s' %scene, folder='LandsatData', region=roi, scale=10)

Exporting LC08_140042_20200115 ...
Exporting LC08_140042_20200131 ...
Exporting LC08_140042_20200216 ...
Exporting LC08_140042_20200303 ...
Exporting LC08_140042_20200319 ...
Exporting LC08_140042_20200404 ...
Exporting LC08_140042_20200420 ...
Exporting LC08_140042_20200506 ...
Exporting LC08_140042_20200607 ...


In [ ]:
pip install pyrsgis

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')
%cd /content/drive/My Drive/LandsatData/

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).
/content/drive/My Drive/LandsatData


In [ ]:
from pyrsgis import raster
import numpy as np
import math
for scene in image_scene[0:1]:
  file = scene+'.tif'
  print(file)
  ds, RedBand = raster.read(file, bands=4)
  ds, NIRBand = raster.read(file, bands=5)
  eq1 =2*NIRBand+1
  eq2 = (2*NIRBand+1)
  eq3 = 8*(NIRBand-RedBand)
  eq4 = np.sqrt(eq2-eq3)
  eq5 = 1/2*(eq1-eq4)
  print(eq2)
  print(eq3)
  MSAVI = 1/2*(2*NIRBand+1-np.sqrt((2*NIRBand+1)**2-8*(NIRBand-RedBand)))
  #raster.export(MSAVI, ds, '/content/drive/My Drive/LandsatData/NDVI_'+scene+'.tif', dtype='float64', bands='all') 
#print('landsat3.tif')

LC08_140042_20200115.tif
[[47071 47071 47159 47159 47159 47099 47099 47099 47329 47329]
 [46377 46377 46425 46425 46425 46971 46971 46971 47385 47385]
 [46377 46377 46425 46425 46425 46971 46971 46971 47385 47385]
 [46377 46377 46425 46425 46425 46971 46971 46971 47385 47385]
 [45831 45831 46439 46439 46439 47507 47507 47507 48019 48019]
 [45831 45831 46439 46439 46439 47507 47507 47507 48019 48019]
 [45831 45831 46439 46439 46439 47507 47507 47507 48019 48019]
 [46831 46831 47709 47709 47709 48141 48141 48141 48331 48331]
 [46831 46831 47709 47709 47709 48141 48141 48141 48331 48331]
 [46831 46831 47709 47709 47709 48141 48141 48141 48331 48331]]
[[21960 21960 21920 21920 21920 21808 21808 21808 22008 22008]
 [21608 21608 21040 21040 21040 21064 21064 21064 21600 21600]
 [21608 21608 21040 21040 21040 21064 21064 21064 21600 21600]
 [21608 21608 21040 21040 21040 21064 21064 21064 21600 21600]
 [21056 21056 21104 21104 21104 20952 20952 20952 21664 21664]
 [21056 21056 21104 21104 211

In [ ]:
#import numpy as np
#MSAVI = 1/2*(2*NIRBand+1-np.sqrt((2*NIRBand+1)^2-8*(NIRBand-RedBand)))
#raster.export(MSAVI, ds, '/content/drive/My Drive/export/MSAVI_%s.tif'%scene, dtype='int', bands='all') 

In [ ]:
array = np.array([[47071,345678,44863],[12344,36548,24535]])